FROM nodered/node-red-docker
RUN npm install node-red-node-random
RUN npm install node-red-node-smooth
RUN npm install node-red-contrib-blynk-websockets
RUN npm install node-red-contrib-elasticsearch3
RUN npm install node-red-node-pushover
RUN npm install node-red-contrib-store-reviews
RUN npm install node-red-dashboard
